env: "prod"
allow_origins:
  - 
http_server:
  address: "localhost:8000"
  timeout: 5s
  idle_timeout: 30s
db:
  host: "localhost"
  port: 5436
  username: "ipbuild"
  dbname: "unet"
  sslmode: "disable"
redis:
  username: "ipbuild-unet"
  address: "localhost:6380"
  db: 0
  ttl:
    user_profile: 15m
    blacklist: 5m
    auth_timeout: 5m
token:
  access_ttl: 15m
  refresh_ttl: 168h
smtp:
  host: "smtp.ya.ru"
  port: 465
