// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admins.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addAdmin = `-- name: AddAdmin :exec
INSERT INTO admins (user_id) VALUES ($1::uuid) ON CONFLICT DO NOTHING
`

func (q *Queries) AddAdmin(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, addAdmin, dollar_1)
	return err
}

const isAdmin = `-- name: IsAdmin :one
SELECT EXISTS(SELECT 1 FROM admins WHERE user_id = $1::uuid) AS is_admin
`

func (q *Queries) IsAdmin(ctx context.Context, dollar_1 uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isAdmin, dollar_1)
	var is_admin bool
	err := row.Scan(&is_admin)
	return is_admin, err
}

const removeAdmin = `-- name: RemoveAdmin :exec
DELETE FROM admins WHERE user_id = $1::uuid
`

func (q *Queries) RemoveAdmin(ctx context.Context, dollar_1 uuid.UUID) error {
	_, err := q.db.Exec(ctx, removeAdmin, dollar_1)
	return err
}
