// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Case struct {
	ID          int64       `json:"id"`
	Title       string      `json:"title"`
	Description string      `json:"description"`
	Label       pgtype.Text `json:"label"`
	Photo       pgtype.Text `json:"photo"`
}

type CaseStat struct {
	ID     int64  `json:"id"`
	CaseID int64  `json:"case_id"`
	Value  string `json:"value"`
	Label  string `json:"label"`
}

type Direction struct {
	ID          int32       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
}

type JobDirection struct {
	ID          int32    `json:"id"`
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
	Description string   `json:"description"`
}

type LinkUserWithPlan struct {
	UserID uuid.UUID `json:"user_id"`
	PlanID uuid.UUID `json:"plan_id"`
}

type Plan struct {
	ID              uuid.UUID          `json:"id"`
	FullName        pgtype.Text        `json:"full_name"`
	Direction       int32              `json:"direction"`
	TaskDescription pgtype.Text        `json:"task_description"`
	Email           string             `json:"email"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID             uuid.UUID          `json:"id"`
	Username       pgtype.Text        `json:"username"`
	FullName       pgtype.Text        `json:"full_name"`
	Email          string             `json:"email"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	HashedPassword string             `json:"hashed_password"`
	Role           pgtype.Text        `json:"role"`
}

type UserRespond struct {
	ID          uuid.UUID          `json:"id"`
	FullName    string             `json:"full_name"`
	PhoneNumber pgtype.Text        `json:"phone_number"`
	Email       string             `json:"email"`
	City        pgtype.Text        `json:"city"`
	Exp         pgtype.Text        `json:"exp"`
	Description pgtype.Text        `json:"description"`
	Resume      pgtype.Text        `json:"resume"`
	VacancyID   uuid.UUID          `json:"vacancy_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Vacancy struct {
	ID          uuid.UUID          `json:"id"`
	Jd          int32              `json:"jd"`
	Name        pgtype.Text        `json:"name"`
	Description pgtype.Text        `json:"description"`
	RequiredExp pgtype.Text        `json:"required_exp"`
	PayDay      float64            `json:"pay_day"`
	Skills      []string           `json:"skills"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type VacancyWithJd struct {
	ID            uuid.UUID          `json:"id"`
	Jd            int32              `json:"jd"`
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	RequiredExp   pgtype.Text        `json:"required_exp"`
	PayDay        float64            `json:"pay_day"`
	Skills        []string           `json:"skills"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	JdName        string             `json:"jd_name"`
	JdTags        []string           `json:"jd_tags"`
	JdDescription string             `json:"jd_description"`
}
