// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getPlan = `-- name: GetPlan :one
SELECT id, full_name, direction, task_description, email, created_at FROM plan WHERE id=$1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Direction,
		&i.TaskDescription,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getResponseFromRequest = `-- name: GetResponseFromRequest :one
SELECT user_id, plan_id FROM link_user_with_plan WHERE plan_id=$1
`

func (q *Queries) GetResponseFromRequest(ctx context.Context, planID uuid.UUID) (LinkUserWithPlan, error) {
	row := q.db.QueryRow(ctx, getResponseFromRequest, planID)
	var i LinkUserWithPlan
	err := row.Scan(&i.UserID, &i.PlanID)
	return i, err
}

const requestPlan = `-- name: RequestPlan :one
INSERT INTO plan (full_name, direction, task_description, email) VALUES ($1, $2, $3, $4) RETURNING id, full_name, direction, task_description, email, created_at
`

type RequestPlanParams struct {
	FullName        pgtype.Text `json:"full_name"`
	Direction       int32       `json:"direction"`
	TaskDescription pgtype.Text `json:"task_description"`
	Email           string      `json:"email"`
}

func (q *Queries) RequestPlan(ctx context.Context, arg RequestPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, requestPlan,
		arg.FullName,
		arg.Direction,
		arg.TaskDescription,
		arg.Email,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Direction,
		&i.TaskDescription,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
