// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPlans = `-- name: CountPlans :one
SELECT COUNT(*) FROM plans
`

func (q *Queries) CountPlans(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPlans)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLinkRequest = `-- name: CreateLinkRequest :exec
INSERT INTO link_user_with_plan (user_id, plan_id) VALUES ($1, $2)
`

type CreateLinkRequestParams struct {
	UserID uuid.UUID `json:"user_id"`
	PlanID uuid.UUID `json:"plan_id"`
}

func (q *Queries) CreateLinkRequest(ctx context.Context, arg CreateLinkRequestParams) error {
	_, err := q.db.Exec(ctx, createLinkRequest, arg.UserID, arg.PlanID)
	return err
}

const getAllPlans = `-- name: GetAllPlans :many
SELECT id, full_name, direction, task_description, email, created_at FROM plans LIMIT $1 OFFSET $2
`

type GetAllPlansParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetAllPlans(ctx context.Context, arg GetAllPlansParams) ([]Plan, error) {
	rows, err := q.db.Query(ctx, getAllPlans, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Plan{}
	for rows.Next() {
		var i Plan
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.Direction,
			&i.TaskDescription,
			&i.Email,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDirection = `-- name: GetDirection :one
SELECT name FROM directions WHERE id=$1 LIMIT 1
`

func (q *Queries) GetDirection(ctx context.Context, id int32) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getDirection, id)
	var name pgtype.Text
	err := row.Scan(&name)
	return name, err
}

const getPlan = `-- name: GetPlan :one
SELECT id, full_name, direction, task_description, email, created_at FROM plans WHERE id=$1 LIMIT 1
`

func (q *Queries) GetPlan(ctx context.Context, id uuid.UUID) (Plan, error) {
	row := q.db.QueryRow(ctx, getPlan, id)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Direction,
		&i.TaskDescription,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const getResponseFromRequest = `-- name: GetResponseFromRequest :one
SELECT user_id, plan_id FROM link_user_with_plan WHERE plan_id=$1 LIMIT 1
`

func (q *Queries) GetResponseFromRequest(ctx context.Context, planID uuid.UUID) (LinkUserWithPlan, error) {
	row := q.db.QueryRow(ctx, getResponseFromRequest, planID)
	var i LinkUserWithPlan
	err := row.Scan(&i.UserID, &i.PlanID)
	return i, err
}

const getUserPlan = `-- name: GetUserPlan :one
SELECT p.id, p.full_name, p.direction, p.task_description, p.email, p.created_at, u.id, u.username, u.full_name, u.email, u.created_at, u.updated_at, u.hashed_password, u.role
FROM plans p
    INNER JOIN link_user_with_plan up ON p.id=up.plan_id
    INNER JOIN users u ON up.user_id=u.id
WHERE
    ($1::varchar IS NULL OR u.id=$1::varchar)
  AND p.id=$2
`

type GetUserPlanParams struct {
	UserID pgtype.Text `json:"user_id"`
	PlanID uuid.UUID   `json:"plan_id"`
}

type GetUserPlanRow struct {
	Plan Plan `json:"plan"`
	User User `json:"user"`
}

func (q *Queries) GetUserPlan(ctx context.Context, arg GetUserPlanParams) (GetUserPlanRow, error) {
	row := q.db.QueryRow(ctx, getUserPlan, arg.UserID, arg.PlanID)
	var i GetUserPlanRow
	err := row.Scan(
		&i.Plan.ID,
		&i.Plan.FullName,
		&i.Plan.Direction,
		&i.Plan.TaskDescription,
		&i.Plan.Email,
		&i.Plan.CreatedAt,
		&i.User.ID,
		&i.User.Username,
		&i.User.FullName,
		&i.User.Email,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User.HashedPassword,
		&i.User.Role,
	)
	return i, err
}

const requestPlan = `-- name: RequestPlan :one
INSERT INTO plans (full_name, direction, task_description, email) VALUES ($1, $2, $3, $4) RETURNING id, full_name, direction, task_description, email, created_at
`

type RequestPlanParams struct {
	FullName        pgtype.Text `json:"full_name"`
	Direction       int32       `json:"direction"`
	TaskDescription pgtype.Text `json:"task_description"`
	Email           string      `json:"email"`
}

func (q *Queries) RequestPlan(ctx context.Context, arg RequestPlanParams) (Plan, error) {
	row := q.db.QueryRow(ctx, requestPlan,
		arg.FullName,
		arg.Direction,
		arg.TaskDescription,
		arg.Email,
	)
	var i Plan
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Direction,
		&i.TaskDescription,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
