// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, full_name, email, hashed_password) VALUES ($1, $2, $3, $4) RETURNING id, username, full_name, email, created_at, updated_at, hashed_password
`

type CreateUserParams struct {
	Username       pgtype.Text `json:"username"`
	FullName       pgtype.Text `json:"full_name"`
	Email          string      `json:"email"`
	HashedPassword string      `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.HashedPassword,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, full_name, email, created_at, updated_at, hashed_password FROM users  WHERE ($1::uuid IS NULL OR id = $1::uuid)
                       AND ($2::varchar IS NULL OR username=$2::varchar)
                       AND ($3::varchar IS NULL OR email=$3::varchar)
`

type GetUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Username pgtype.Text `json:"username"`
	Email    pgtype.Text `json:"email"`
}

func (q *Queries) GetUser(ctx context.Context, arg GetUserParams) (User, error) {
	row := q.db.QueryRow(ctx, getUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET hashed_password = $1,
    updated_at = now()
WHERE ($2::uuid IS NULL OR id=$2::uuid)
AND ($3::varchar IS NULL OR username=$3::varchar)
RETURNING id, username, full_name, email, created_at, updated_at, hashed_password
`

type UpdatePasswordParams struct {
	NewPassword string      `json:"new_password"`
	ID          pgtype.UUID `json:"id"`
	Username    pgtype.Text `json:"username"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.NewPassword, arg.ID, arg.Username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.FullName,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
	)
	return i, err
}

const userExists = `-- name: UserExists :one
SELECT EXISTS(SELECT 1
              FROM users
              WHERE ($1::uuid IS NULL OR id = $1::uuid)
              AND ($2::varchar IS NULL OR username=$2::varchar)
              AND ($3::varchar IS NULL OR email=$3::varchar)
              AND (hashed_password=$4::varchar))
`

type UserExistsParams struct {
	ID       pgtype.UUID `json:"id"`
	Username pgtype.Text `json:"username"`
	Email    pgtype.Text `json:"email"`
	Password string      `json:"password"`
}

func (q *Queries) UserExists(ctx context.Context, arg UserExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, userExists,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.Password,
	)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
