// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacancies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createVacancy = `-- name: CreateVacancy :one
INSERT INTO vacancies (jd, name, description, required_exp, pay_day, skills) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at
`

type CreateVacancyParams struct {
	Jd          int32         `json:"jd"`
	Name        pgtype.Text   `json:"name"`
	Description pgtype.Text   `json:"description"`
	RequiredExp pgtype.Float8 `json:"required_exp"`
	PayDay      float64       `json:"pay_day"`
	Skills      []string      `json:"skills"`
}

func (q *Queries) CreateVacancy(ctx context.Context, arg CreateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, createVacancy,
		arg.Jd,
		arg.Name,
		arg.Description,
		arg.RequiredExp,
		arg.PayDay,
		arg.Skills,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const existsVacancy = `-- name: ExistsVacancy :one
SELECT EXISTS(SELECT 1 FROM vacancies WHERE id=$1)
`

func (q *Queries) ExistsVacancy(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsVacancy, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getVacancies = `-- name: GetVacancies :many
SELECT id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at FROM vacancies LIMIT $1 OFFSET $2
`

type GetVacanciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetVacancies(ctx context.Context, arg GetVacanciesParams) ([]Vacancy, error) {
	rows, err := q.db.Query(ctx, getVacancies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vacancy{}
	for rows.Next() {
		var i Vacancy
		if err := rows.Scan(
			&i.ID,
			&i.Jd,
			&i.Name,
			&i.Description,
			&i.RequiredExp,
			&i.PayDay,
			&i.Skills,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVacancy = `-- name: GetVacancy :one
SELECT id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at FROM vacancies WHERE
                            ($1::uuid IS NULL OR id=$1::uuid)
                            AND ($2::varchar IS NULL OR id=$2::varchar)
`

type GetVacancyParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) GetVacancy(ctx context.Context, arg GetVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, getVacancy, arg.ID, arg.Name)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeVacancy = `-- name: RemoveVacancy :exec
DELETE FROM vacancies WHERE
                          ($1::uuid IS NULL OR id=$1::uuid)
                        AND($2::varchar IS NULL OR name=$2::varchar)
`

type RemoveVacancyParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) RemoveVacancy(ctx context.Context, arg RemoveVacancyParams) error {
	_, err := q.db.Exec(ctx, removeVacancy, arg.ID, arg.Name)
	return err
}

const respondToVacancy = `-- name: RespondToVacancy :one
INSERT INTO user_responds (full_name, phone_number, email, city, exp, description, resume, vacancy_id)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8) RETURNING id
`

type RespondToVacancyParams struct {
	FullName    string      `json:"full_name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	Email       string      `json:"email"`
	City        pgtype.Text `json:"city"`
	Exp         pgtype.Text `json:"exp"`
	Description pgtype.Text `json:"description"`
	Resume      pgtype.Text `json:"resume"`
	VacancyID   uuid.UUID   `json:"vacancy_id"`
}

func (q *Queries) RespondToVacancy(ctx context.Context, arg RespondToVacancyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, respondToVacancy,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.City,
		arg.Exp,
		arg.Description,
		arg.Resume,
		arg.VacancyID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateVacancy = `-- name: UpdateVacancy :one
UPDATE vacancies SET jd=$1, name=$2, description=$3, required_exp=$4, pay_day=$5, skills=$6, updated_at=now() RETURNING id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at
`

type UpdateVacancyParams struct {
	Jd          int32         `json:"jd"`
	Name        pgtype.Text   `json:"name"`
	Description pgtype.Text   `json:"description"`
	RequiredExp pgtype.Float8 `json:"required_exp"`
	PayDay      float64       `json:"pay_day"`
	Skills      []string      `json:"skills"`
}

func (q *Queries) UpdateVacancy(ctx context.Context, arg UpdateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, updateVacancy,
		arg.Jd,
		arg.Name,
		arg.Description,
		arg.RequiredExp,
		arg.PayDay,
		arg.Skills,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
