// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vacancies.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createJobDirection = `-- name: CreateJobDirection :one
INSERT INTO job_directions (name, tags, description) VALUES ($1::varchar, $2::text[], $3::text) RETURNING id, name, tags, description
`

type CreateJobDirectionParams struct {
	Name        string   `json:"name"`
	Tags        []string `json:"tags"`
	Description string   `json:"description"`
}

func (q *Queries) CreateJobDirection(ctx context.Context, arg CreateJobDirectionParams) (JobDirection, error) {
	row := q.db.QueryRow(ctx, createJobDirection, arg.Name, arg.Tags, arg.Description)
	var i JobDirection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Description,
	)
	return i, err
}

const createVacancy = `-- name: CreateVacancy :one
INSERT INTO vacancies (jd, name, description, required_exp, pay_day, skills) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at
`

type CreateVacancyParams struct {
	Jd          int32       `json:"jd"`
	Name        pgtype.Text `json:"name"`
	Description pgtype.Text `json:"description"`
	RequiredExp pgtype.Text `json:"required_exp"`
	PayDay      float64     `json:"pay_day"`
	Skills      []string    `json:"skills"`
}

func (q *Queries) CreateVacancy(ctx context.Context, arg CreateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, createVacancy,
		arg.Jd,
		arg.Name,
		arg.Description,
		arg.RequiredExp,
		arg.PayDay,
		arg.Skills,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJD = `-- name: GetJD :one
SELECT id, name, tags, description FROM job_directions WHERE id=$1::bigserial LIMIT 1
`

func (q *Queries) GetJD(ctx context.Context, id int64) (JobDirection, error) {
	row := q.db.QueryRow(ctx, getJD, id)
	var i JobDirection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Description,
	)
	return i, err
}

const getJDs = `-- name: GetJDs :many
SELECT id, name, tags, description FROM job_directions LIMIT $1 OFFSET $2
`

type GetJDsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetJDs(ctx context.Context, arg GetJDsParams) ([]JobDirection, error) {
	rows, err := q.db.Query(ctx, getJDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []JobDirection{}
	for rows.Next() {
		var i JobDirection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tags,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRespondVacancies = `-- name: GetRespondVacancies :many
SELECT id, full_name, phone_number, email, city, exp, description, resume, vacancy_id, created_at FROM user_responds LIMIT $1 OFFSET $2
`

type GetRespondVacanciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetRespondVacancies(ctx context.Context, arg GetRespondVacanciesParams) ([]UserRespond, error) {
	rows, err := q.db.Query(ctx, getRespondVacancies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRespond{}
	for rows.Next() {
		var i UserRespond
		if err := rows.Scan(
			&i.ID,
			&i.FullName,
			&i.PhoneNumber,
			&i.Email,
			&i.City,
			&i.Exp,
			&i.Description,
			&i.Resume,
			&i.VacancyID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRespondVacancy = `-- name: GetRespondVacancy :one
SELECT id, full_name, phone_number, email, city, exp, description, resume, vacancy_id, created_at FROM user_responds WHERE id=$1 LIMIT 1
`

func (q *Queries) GetRespondVacancy(ctx context.Context, id uuid.UUID) (UserRespond, error) {
	row := q.db.QueryRow(ctx, getRespondVacancy, id)
	var i UserRespond
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.PhoneNumber,
		&i.Email,
		&i.City,
		&i.Exp,
		&i.Description,
		&i.Resume,
		&i.VacancyID,
		&i.CreatedAt,
	)
	return i, err
}

const getVacancies = `-- name: GetVacancies :many
SELECT v.id, v.jd, v.name, v.description, v.required_exp, v.pay_day, v.skills, v.created_at, v.updated_at, jd.name as jd_name, jd.tags as jd_tags, jd.description as jd_description FROM vacancies v JOIN job_directions jd on v.jd=jd.id LIMIT $1 OFFSET $2
`

type GetVacanciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type VacancyWithJd struct {
	ID            uuid.UUID          `json:"id"`
	Jd            int32              `json:"jd"`
	Name          pgtype.Text        `json:"name"`
	Description   pgtype.Text        `json:"description"`
	RequiredExp   pgtype.Text        `json:"required_exp"`
	PayDay        float64            `json:"pay_day"`
	Skills        []string           `json:"skills"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	JdName        string             `json:"jd_name"`
	JdTags        []string           `json:"jd_tags"`
	JdDescription string             `json:"jd_description"`
}

func (q *Queries) GetVacancies(ctx context.Context, arg GetVacanciesParams) ([]VacancyWithJd, error) {
	rows, err := q.db.Query(ctx, getVacancies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VacancyWithJd{}
	for rows.Next() {
		var i VacancyWithJd
		if err := rows.Scan(
			&i.ID,
			&i.Jd,
			&i.Name,
			&i.Description,
			&i.RequiredExp,
			&i.PayDay,
			&i.Skills,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.JdName,
			&i.JdTags,
			&i.JdDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVacancy = `-- name: GetVacancy :one
SELECT v.id, v.jd, v.name, v.description, v.required_exp, v.pay_day, v.skills, v.created_at, v.updated_at, jd.name as jd_name, jd.tags as jd_tags, jd.description as jd_description FROM vacancies v JOIN job_directions jd ON v.jd=jd.id  WHERE
                            ($1::uuid IS NULL OR id=$1::uuid)
                            AND ($2::varchar IS NULL OR name=$2::varchar)
`

type GetVacancyParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) GetVacancy(ctx context.Context, arg GetVacancyParams) (VacancyWithJd, error) {
	row := q.db.QueryRow(ctx, getVacancy, arg.ID, arg.Name)
	var i VacancyWithJd
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.JdName,
		&i.JdTags,
		&i.JdDescription,
	)
	return i, err
}

const removeJobDirection = `-- name: RemoveJobDirection :exec
DELETE FROM job_directions WHERE id=$1::bigserial
`

func (q *Queries) RemoveJobDirection(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, removeJobDirection, id)
	return err
}

const removeVacancy = `-- name: RemoveVacancy :exec
DELETE FROM vacancies WHERE
                          ($1::uuid IS NULL OR id=$1::uuid)
                        AND($2::varchar IS NULL OR name=$2::varchar)
`

type RemoveVacancyParams struct {
	ID   pgtype.UUID `json:"id"`
	Name pgtype.Text `json:"name"`
}

func (q *Queries) RemoveVacancy(ctx context.Context, arg RemoveVacancyParams) error {
	_, err := q.db.Exec(ctx, removeVacancy, arg.ID, arg.Name)
	return err
}

const respondToVacancy = `-- name: RespondToVacancy :one
INSERT INTO user_responds (full_name, phone_number, email, city, exp, description, resume, vacancy_id)
VALUES (
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7,
        $8) RETURNING id
`

type RespondToVacancyParams struct {
	FullName    string      `json:"full_name"`
	PhoneNumber pgtype.Text `json:"phone_number"`
	Email       string      `json:"email"`
	City        pgtype.Text `json:"city"`
	Exp         pgtype.Text `json:"exp"`
	Description pgtype.Text `json:"description"`
	Resume      pgtype.Text `json:"resume"`
	VacancyID   uuid.UUID   `json:"vacancy_id"`
}

func (q *Queries) RespondToVacancy(ctx context.Context, arg RespondToVacancyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, respondToVacancy,
		arg.FullName,
		arg.PhoneNumber,
		arg.Email,
		arg.City,
		arg.Exp,
		arg.Description,
		arg.Resume,
		arg.VacancyID,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const updateJobDirection = `-- name: UpdateJobDirection :one
UPDATE job_directions SET name=$1::varchar, tags=$2::text[], description=$3::text
                      WHERE id=$4::bigserial RETURNING id, name, tags, description
`

type UpdateJobDirectionParams struct {
	Name        pgtype.Text `json:"name"`
	Tags        []string    `json:"tags"`
	Description pgtype.Text `json:"description"`
	ID          int64       `json:"id"`
}

func (q *Queries) UpdateJobDirection(ctx context.Context, arg UpdateJobDirectionParams) (JobDirection, error) {
	row := q.db.QueryRow(ctx, updateJobDirection,
		arg.Name,
		arg.Tags,
		arg.Description,
		arg.ID,
	)
	var i JobDirection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Tags,
		&i.Description,
	)
	return i, err
}

const updateVacancy = `-- name: UpdateVacancy :one
UPDATE vacancies SET jd=$1, name=$6::varchar, description=$2, required_exp=$3, pay_day=$4, skills=$5, updated_at=now()  WHERE
    ($7::uuid IS NULL OR id=$7::uuid)
                                                                                                                 AND($8::varchar IS NULL OR name=$8::varchar) RETURNING id, jd, name, description, required_exp, pay_day, skills, created_at, updated_at
`

type UpdateVacancyParams struct {
	Jd          int32       `json:"jd"`
	Description pgtype.Text `json:"description"`
	RequiredExp pgtype.Text `json:"required_exp"`
	PayDay      float64     `json:"pay_day"`
	Skills      []string    `json:"skills"`
	NewName     string      `json:"new_name"`
	ID          pgtype.UUID `json:"id"`
	Name        pgtype.Text `json:"name"`
}

func (q *Queries) UpdateVacancy(ctx context.Context, arg UpdateVacancyParams) (Vacancy, error) {
	row := q.db.QueryRow(ctx, updateVacancy,
		arg.Jd,
		arg.Description,
		arg.RequiredExp,
		arg.PayDay,
		arg.Skills,
		arg.NewName,
		arg.ID,
		arg.Name,
	)
	var i Vacancy
	err := row.Scan(
		&i.ID,
		&i.Jd,
		&i.Name,
		&i.Description,
		&i.RequiredExp,
		&i.PayDay,
		&i.Skills,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
